version: 2
updates:
  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, javascript]

  - package-ecosystem: npm
    directory: /electron
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, javascript, electron]

  - package-ecosystem: pip
    directory: /daemon
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, python]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, ci]
