---
name: GitHub Pages — Documentation

on:
    push:
        branches: [main]
        paths:
            - docs/**
            - mkdocs.yml
    workflow_dispatch:

concurrency:
    group: pages-${{ github.ref }}
    cancel-in-progress: false

jobs:
    call:
        uses: chrysa/github-actions/.github/workflows/pages.yml@v1.2.3